stages:
  - build
  - deploy

variables:
  APP_NAME: "nodejs-express-mysql"
  DOCKER_IMAGE: "registry.gitlab.com/bernabaris/nodejs-express-mysql"
  DOCKER_TAG: 1.0.0
  GCP_PROCET_ID: "nodejs-express-project"
  GCP_PROJECT_NAME: "nodejs-express-project"
  GKE_CLUSTER_NAME: "nodejs-express-cluster"
  GKE_CLUSTER_ZONE: "us-central1-c"
  HELM_VERSION: 3.16.3
  NAMESPACE: default

build:
  stage: build
  image:
    name: docker:19.03.12
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Building application..."
    - docker build -t $DOCKER_IMAGE:$DOCKER_TAG .
    - docker push $DOCKER_IMAGE:$DOCKER_TAG

deploy:
  stage: deploy
  image:
    name: google/cloud-sdk
  script:
    - echo "Deploying application with Helm..."
    - echo "$GCP_SERVICE_ACCOUNT_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project $GCP_PROJECT_NAME
    - gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $GKE_CLUSTER_ZONE --project $GCP_PROJECT_NAME

    - curl -L https://get.helm.sh/helm-v$HELM_VERSION-linux-amd64.tar.gz | tar xz
    - mv linux-amd64/helm /usr/bin/
    - helm upgrade ${APP_NAME} ./chart --install --namespace $NAMESPACE
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
