stages:
  - build
  - deploy

variables:
  APP_NAME: "nodejs-express-mysql"
  DOCKER_IMAGE: "registry.gitlab.com/bernabaris/nodejs-express-mysql"
  GCP_PROCET_ID: "nodejs-express-project"
  GKE_CLUSTER_NAME: "nodejs-express-cluster"
  GKE_CLUSTER_ZONE: "us-central1-c"

build:
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Building application..."
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
  tags:
    - macos

deploy:
  stage: deploy
  environment:
    name: production
  image:
    name: google/cloud-sdk:latest
    entrypoint: [""]
  before_script:
    - cat $gcp_key | docker login -u _json_key --password-stdin https://eu.gcr.io
  script:
    - echo "Deploying application with Helm..."
    - gcloud auth activate-service-account --key-file=$GCP_SERVICE_ACCOUNT_KEY
    - gcloud config set project $GCP_PROJECT_ID
    - gcloud container clusters get-credentials $GKE_CLUSTER_NAME --zone $GKE_CLUSTER_ZONE

    - helm upgrade ${APP_NAME} ./charts --install --namespace ${APP_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
