stages:
  - build
  - deploy

variables:
  APP_NAME: "nodejs-express-mysql"

build:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Building application..."
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  tags:
    - macos

deploy:
  stage: deploy
  environment:
    name: production
  image:
    name: alpine/helm:3.2.1
    entrypoint: [""]
  script:
    - echo "Deploying application with Helm..."
    - helm upgrade ${APP_NAME} ./charts --install --namespace ${APP_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always
