stages:
  - build
  - deploy

variables:
  APP_NAME: "nodejs-express-mysql"
  DOCKER_IMAGE: "registry.gitlab.com/bernabaris/nodejs-express-mysql"

build:
  stage: build
  script:
    - echo "Building application..."
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA

deploy:
  stage: deploy
  environment:
    name: production
  script:
    - echo "Deploying application to Kubernetes..."
    - kubectl apply -f deployment.yaml
    - kubectl rollout status deployment/$APP_NAME
