apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nodejs-express.fullname" . }}
  labels: {{- include "nodejs-express.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nodejs-express.selectorLabels" . }}
  template:
    metadata:
      labels:
        {{- include "nodejs-express.selectorLabels" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . }}
      {{- end }}
      serviceAccountName: {{ include "nodejs-express.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . }}
      {{- end }}
