project: default
source:
  repoURL: https://gitlab.com/bernabaris/nodejs-express-mysql.git
  path: chart
  targetRevision: master
destination:
  server: https://kubernetes.default.svc
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: true
